global_vars:
  lr_deg: 5.625
  hr_deg: 1.40625
  var: 2m_temperature
  seed: 3407

data:
  type: era5
  lr_dir: /scratch/izar/hoang/SSL/data/${global_vars.lr_deg}deg/${global_vars.var}
  hr_dir: /scratch/izar/hoang/SSL/data/${global_vars.hr_deg}deg/${global_vars.var}
  stride: 6
  preload: false
  batch_size: 32
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2

model:
  mode: lora
  model_id: dinov3-sat
  upscale: 4
  hidden_dim: 256
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.0

# dinov3-sat config  
training:
  max_epochs: 50
  lr: 5e-5
  decoder_lr: 4e-4
  weight_decay: 1e-2
  patience: 5
  warmup_epochs: 5
  grad_accum_steps: 4
  ckpt_dir: /scratch/izar/hoang/SSL/checkpoints/${data.type}/${model.model_id}/${model.mode}

wandb:
  entity: thainamhoang
  project: SSL Climate
  name: ${model.mode}${model.lora_r}_${model.model_id}_${model.upscale}x_${global_vars.lr_deg}deg_${global_vars.hr_deg}deg